<?php

namespace Tests\Feature;

use Tests\TestCase;

class OrganizationReceiptPresentationTest extends TestCase
{
    public function test_web_receipt_uses_integrated_professional_layout(): void
    {
        $view =
            file_get_contents(
                resource_path(
                    'views/organization-billing/show.blade.php'
                )
            );

        $this->assertIsString(
            $view
        );

        $this->assertStringContainsString(
            'data-subscription-receipt',
            $view
        );

        $this->assertStringContainsString(
            'Official subscription receipt',
            $view
        );

        $this->assertStringContainsString(
            'Verified payment details',
            $view
        );

        $this->assertStringContainsString(
            'data-receipt-verification-metadata',
            $view
        );

        $this->assertStringNotContainsString(
            'mx-auto mt-8 max-w-5xl',
            $view
        );
    }

    public function test_pdf_receipt_places_verification_before_footer(): void
    {
        $view =
            file_get_contents(
                resource_path(
                    'views/pdfs/subscription-receipt.blade.php'
                )
            );

        $this->assertIsString(
            $view
        );

        $verification =
            strpos(
                $view,
                'Verified payment details'
            );

        $footer =
            strpos(
                $view,
                'Generated by the eConsent subscription billing system.'
            );

        $this->assertNotFalse(
            $verification
        );

        $this->assertNotFalse(
            $footer
        );

        $this->assertLessThan(
            $footer,
            $verification
        );

        $this->assertStringContainsString(
            'Official subscription receipt',
            $view
        );

        $this->assertStringContainsString(
            'Payment {{ $receiptStatus }}',
            $view
        );
    }
}
